version: '3.4'

services:
  pineapple.grpc.mock.rpchost:
    image: pineappleslice/grpc.mock:latest
    ports:
      - 5001:5001
      - 5002:5002
    volumes:
      - ./stub:/stub
      - ./proto:/proto
    environment:
      - Serilog__MinimumLevel__Default=Verbose