version: '3.4'

services:
  pineapple.grpc.mock.rpchost:
    image: pineappleslice/grpc.mock:0.0.1
    ports:
      - 5001:5001
      - 5002:5002
    volumes:
      - ./stub:/stub
      - ./proto:/proto