version: '3.4'

services:
  pineapple.grpc.mock.rpchost:
    image: pineapple.grpc.mock.rpchost
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5001:5001
      - 5002:5002
    volumes:
      - ./stub:/stub
      - ./proto:/proto